### ISSUE TITLE
Google OAuth2 Access

### ISSUE THREAD

**Issue by mikebz** [ciaranj/connect-auth#85] opened 2012-03-08 00:44 UTC
Does anyone have a sample of code for Google OAuth2 access to docs or calendar?

Sorry to be a total noob but I am getting up to speed on express, node and this library.  

If no one has something they can share - I can figure it out, but otherwise I was hoping to stand on the shoulders of the giants.

**Comment by ciaranj** [comment] 2012-03-08 09:35
Sure, should be pretty 'easy'.  With this package.json (note the versions of the libraries does currently matter) :

```
 { "name" : "my-project"
 , "version" : "1.0.0"
 , "dependencies" : { "express" : "2.5.4", "connect-auth" :"0.4.2", "oauth": "0.9.6" } 
 }
```

and this code:

```
var  auth= require('connect-auth')
   , express= require('express')
   , OAuth= require("oauth").OAuth2;

var g2id= "";
var g2Secret= "";
var g2CallbackAddress= "http://testtwitter.com/oauth2callback";

var oauthUtil= new OAuth(g2id, g2Secret,  "", "https://accounts.google.com/o/oauth2/auth", "https://accounts.google.com/o/oauth2/token");

var app = express.createServer();
app.use(express.cookieParser());
app.use(express.session({ secret: "keyboard cat" }));
app.use( auth({strategies: [auth.Google2({appId : g2id, appSecret: g2Secret, callback: g2CallbackAddress, scope:     "https://www.google.com/calendar/feeds/ https://www.google.com/m8/feeds/"})], 
                    trace: true,
        firstLoginHandler: function( authContext, executionResult, callback ) {
          console.log(authContext.request.session["access_token"] )
          oauthUtil.get("https://www.google.com/calendar/feeds/default/owncalendars/full", authContext.request.session["access_token"],  function( error, data ) {
            console.log( data )
          });

          if( callback ) callback( null, true ); 
        }}));

// Horribly hacky demonstration route (would normally suggest writing a lightweight middleware
// to manage which routes get authenticated etc. See the example app on github for good examples)
app.get('/', function(req, res){
    if( req.isAuthenticated() ){
      res.send('Hello World');
    } else {
      req.authenticate("google2", function(err, authenticated){
      });
    }
});

app.listen(80);
```

I can get a list of all the signed in user's calendars .. does that help ?

**Comment by mikebz** [comment] 2012-03-08 20:04
Thanks that got me a long way.  I was actually able to see the Auth window so that was good.  However the authentication does seem to fail eventually.  I am debugging it on my end but I was wondering if anyone had any ideas.  Here is the same code (essentially)

```
var  auth= require('connect-auth')
    , express= require('express')
    , OAuth= require("oauth").OAuth2;

var g2id= "removed.....";
var g2Secret= "removed.....";
var g2CallbackAddress= "http://localhost:3000/oauth2callback";
var oauthUtil= new OAuth(g2id, g2Secret,  "", "https://accounts.google.com/o/oauth2/auth", "https://accounts.google.com/o/oauth2/token");

var app = express.createServer();
app.use(express.cookieParser());
app.use(express.session({ secret: "privet!" }));
app.use( auth(
              {
                strategies:
                  [ auth.Google2( {appId : g2id, appSecret: g2Secret, callback: g2CallbackAddress,
                        scope: "https://www.google.com/calendar/feeds/ https://www.google.com/m8/feeds/"})],
                        trace: true,
                        firstLoginHandler:
                        function( authContext, executionResult, callback ) {
                          console.log(authContext.request.session["access_token"] );
                          oauthUtil.get("https://www.google.com/calendar/feeds/default/owncalendars/full", authContext.request.session["access_token"],  function( error, data ) {
                          console.log( data );
                        });
        if( callback ) callback( null, true );
}}));

app.get('/', function(req, res){
  console.log("in app.get");
  if( req.isAuthenticated() ){
    res.send('Hello World');
  } else {
    req.authenticate("google2", function(err, authenticated){
      console.log("in authenticate");
    });
  }
});

app.listen(3000);
```

Output:

```
^CSilverFir-2:google-sample mike$ node app.js 
in app.get
11:36:05-019 [vOzWQM] >>> Authenticating (localhost:3000/)
11:36:05-021 [vOzWQM] *** google2: Attempting authentication with: google2
11:36:05-021 [vOzWQM] *** google2: Phase 1/2 - Redirecting to Google Authorizing url
11:36:05-021 [vOzWQM] *** google2: Redirecting to: https://accounts.google.com/o/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth2callback&scope=https%3A%2F%2Fwww.google.com%2Fcalendar%2Ffeeds%2F%20https%3A%2F%2Fwww.google.com%2Fm8%2Ffeeds%2F&response_type=code&client_id=207188398174.apps.googleusercontent.com&type=web_server
11:36:05-022 [vOzWQM] *** google2: Tested all strategies
11:36:05-022 [vOzWQM] <<< Authentication ongoing (Requires browser interaction)
in authenticate
11:36:05-223 [vOzWQM] >>> Authenticating (localhost:3000/oauth2callback?code=k....removed.....
11:36:05-223 [vOzWQM] *** google2: Attempting authentication with: google2
11:36:05-223 [vOzWQM] *** google2: Phase 2/2 : Requesting an OAuth access token.
11:36:06-286 [vOzWQM] *** google2: Error retrieving the contact details =>{"statusCode":404,"data":"Contact not found."}
11:36:06-286 [vOzWQM] *** google2: Failed
11:36:06-287 [vOzWQM] *** google2: Tested all strategies
11:36:06-287 [vOzWQM] <<< Authentication failed
in app.get
11:36:06-295 [vOzWQM] >>> Authenticating (localhost:3000/)
11:36:06-295 [vOzWQM] *** google2: Attempting authentication with: google2
11:36:06-295 [vOzWQM] *** google2: Failed
11:36:06-295 [vOzWQM] *** google2: Tested all strategies
11:36:06-295 [vOzWQM] <<< Authentication failed
in authenticate
in app.get
11:38:06-299 [vOzWQM] >>> Authenticating (localhost:3000/)
11:38:06-300 [vOzWQM] *** google2: Attempting authentication with: google2
11:38:06-300 [vOzWQM] *** google2: Failed
11:38:06-300 [vOzWQM] *** google2: Tested all strategies
11:38:06-300 [vOzWQM] <<< Authentication failed
in authenticate
```

**Comment by ciaranj** [comment] 2012-03-08 20:29
Yeah we se this quite often (I don't get it!) but others do, the issue is with : 

```
6-286 [vOzWQM] *** google2: Error retrieving the contact details =>{"statusCode":404,"data":"Contact not found."}
```

For example issue #73 and this pull request: https://github.com/ciaranj/connect-auth/commit/b5623dd8f77d3134dbb42531eca210c23c1127fd  professes to fix the issue.. (but that fix [something I used to do] will be really slow)

Could really do with understanding why the hell I don't get this issue but (it would seem) lots of others do ! :(

**Comment by ciaranj** [comment] 2012-03-08 22:59
Ok.  This is now all resolved in 0.4.3 and in 0.5.1 the package.json should look like: 

```
{ "name" : "my-project"
, "version" : "1.0.0"
, "dependencies" : { "express" : "2.5.4", "connect-auth" :"0.4.3", "oauth": "0.9.6" } 
}
```

and the updated code should look like: 

```
var  auth= require('connect-auth')
   , express= require('express')
   , OAuth= require("oauth").OAuth2;

var g2id= "";
var g2Secret= "";
var g2CallbackAddress= "http://testtwitter.com/oauth2callback";

var oauthUtil= new OAuth(g2id, g2Secret,  "", "https://accounts.google.com/o/oauth2/auth", "https://accounts.google.com/o/oauth2/token");

var app = express.createServer();
app.use(express.cookieParser());
app.use(express.session({ secret: "keyboard cat" }));
app.use( auth({strategies: [auth.Google2({appId : g2id, appSecret: g2Secret, callback: g2CallbackAddress, scope: "https://www.google.com/calendar/feeds/"})], 
                trace: true,
        firstLoginHandler: function( authContext, executionResult, callback ) {
          oauthUtil.get("https://www.google.com/calendar/feeds/default/owncalendars/full", authContext.request.session["access_token"], function( error, data ) {
            console.log( data )
          });
          if( callback ) callback( null, true ); 
        }}));

// Horribly hacky demonstration route (would normally suggest writing a lightweight middleware
// to manage which routes get authenticated etc. See the example app on github for good examples)
app.get('/', function(req, res){
    if( req.isAuthenticated() ){
      res.send('Hello World');
    } else {
      req.authenticate("google2", function(err, authenticated){
      });
    }
});

app.listen(80);
```

**Closed as completed by ciaranj** 2012-03-08 22:59 UTC

**Comment by mikebz** [comment] 2012-03-14 23:06
Confirmed that the example works.  The only issue is that Google has moved their API access to the new googleapis.com so I will try to rework it.  Thanks Ciaran!

**Comment by ciaranj** [comment] 2012-03-14 23:07
blimey, how recent was that?  That code was working just last week!

**Comment by mikebz** [comment] 2012-03-14 23:10
Yes, now it comes back with a moved page and Google is advertising their new V3 APIs: https://developers.google.com/google-apps/calendar/v3/reference/calendars/get

**Comment by mikebz** [comment] 2012-03-14 23:22
actually found an easy fix:

just need to request this: https://www.google.com/calendar/feeds/default/owncalendars/full

This works for now.

The final code is:

```
    var  auth= require('connect-auth'), express= require('express'), OAuth= require("oauth").OAuth2;

    var g2id= "TODO...";
    var g2Secret= "TODO....";
    var g2CallbackAddress= "http://localhost:3000/oauth2callback";

    var oauthUtil= new OAuth(g2id, g2Secret,  "", "https://accounts.google.com/o/oauth2/auth", "https://accounts.google.com/o/oauth2/token");

    var app = express.createServer();
    app.use(express.cookieParser());
    app.use(express.session({ secret: "snoop dog" }));
    app.use( auth({strategies: [auth.Google2({appId : g2id, appSecret: g2Secret, callback: g2CallbackAddress, scope: "https://www.google.com/calendar/feeds/"})],
              trace: true,
            firstLoginHandler: function( authContext, executionResult, callback ) {
              oauthUtil.get("https://www.google.com/calendar/feeds/default/owncalendars/full", authContext.request.session["access_token"], function( error, data ) {
                console.log("reporting API");
                console.log( data )
              });
              if( callback ) callback( null, true );
            }}));

    // Horribly hacky demonstration route (would normally suggest writing a lightweight middleware
    // to manage which routes get authenticated etc. See the example app on github for good examples)
    app.get('/', function(req, res){
    if( req.isAuthenticated() ){
        res.send('Hello World');
    } else {
        req.authenticate("google2", function(err, authenticated){
    });
    }
    });

    app.listen(3000);
```
